#ifndef KEYCODES_H
#define KEYCODES_H

enum KeyNum {
	MAX_NUM_KEYS = 256,

	ESC_KEY = VK_ESCAPE,

	CTRL_KEY = VK_CONTROL,
	ALT_KEY = VK_MENU,
	SHIFT_KEY = VK_SHIFT,
	PAUSE_KEY = VK_PAUSE,
	ENTER_KEY = VK_RETURN
};

#endif	// Header guard